name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install server dependencies
        run: |
          cd server
          npm install

  run-client-tests:
    runs-on: ubuntu-latest
    needs:
      - build-client
      - build-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Run client tests
        run: |
          cd client
          npm test